### ISSUE TITLE
Defines with brackets interpreted as non-constant values

### ISSUE THREAD

**Issue by abeaugustijn** [hivehelsinki/norminette-client#2]
I have come across a bug where a `#define` statement is not interpreted as a constant value, although it is. Examples:
```c
#  define KEY_A ((int)'a')
#  define KEY_UP (65362)
```

**Comment by abeaugustijn** [comment]
Will this be fixed?

**Comment by jgengo** [comment]
Hello, 

This is a server-side issue, that could be fixed. I just don't have the time right now.

If I do change it it will anyway not be applied to the norminette of your school.

**Comment by abeaugustijn** [comment]
So if I understand correctly, this package is a client which talks to our schools own server? (in my case Codam)

**Comment by jgengo** [comment]
This package is a client that communicates with an instance of the Hive Helsinki server hosted on my personal server.

That's why, if I do edit the server behavior for this case, it doesn't mean it would be changed in the Codam server while every school of the network has its own norminette server hosted locally.

I can, of course, once fixed contact every school to give them the update that they can decide to apply or not.

**Comment by jgengo** [comment]
Hello @abeaugustijn,

I've discussed this issue with 42 / Benny it seems unnecessary cast for the first case and also unnecessary parenthesis for the second case.

May I ask you why you did it that way? Just to make we don't miss something.

**Comment by abeaugustijn** [comment]
The parentheses have no functional value as far as I know. The casts may have impact on the functionality. These things are not in any means necessary, I just think it should be allowed to do. It would obviously not be a problem to just rewrite a bit of this, but it would be nice if someday it could be fixed.

**Comment by jgengo** [comment]
I close this issue and let 42 handles that while it's their tool.
